-- TriNova Digital Signatures Migration
-- Integrates Documenso-compatible e-signature workflows into TriNova Client Portal

CREATE TABLE IF NOT EXISTS `signature_requests` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `document_id` INT UNSIGNED NOT NULL,
    `client_id` INT UNSIGNED NOT NULL,
    `entity_id` INT UNSIGNED NULL,
    `created_by_user_id` INT UNSIGNED NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `status` ENUM('draft', 'pending', 'completed', 'declined', 'expired', 'cancelled') NOT NULL DEFAULT 'draft',
    `signing_order` ENUM('parallel', 'sequential') NOT NULL DEFAULT 'parallel',
    `signed_document_id` INT UNSIGNED NULL,
    `qr_token` VARCHAR(64) NULL UNIQUE,
    `allow_drawn_signature` TINYINT(1) NOT NULL DEFAULT 1,
    `allow_typed_signature` TINYINT(1) NOT NULL DEFAULT 1,
    `allow_upload_signature` TINYINT(1) NOT NULL DEFAULT 1,
    `original_checksum_sha256` VARCHAR(64) NULL,
    `signed_checksum_sha256` VARCHAR(64) NULL,
    `expires_at` DATETIME NULL,
    `completed_at` DATETIME NULL,
    `declined_at` DATETIME NULL,
    `decline_reason` TEXT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME NULL,
    INDEX `idx_sig_req_status` (`status`),
    INDEX `idx_sig_req_client` (`client_id`),
    INDEX `idx_sig_req_entity` (`entity_id`),
    INDEX `idx_sig_req_doc` (`document_id`),
    INDEX `idx_sig_req_deleted_at` (`deleted_at`),
    CONSTRAINT `fk_sig_req_doc` FOREIGN KEY (`document_id`) REFERENCES `documents` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_sig_req_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_sig_req_entity` FOREIGN KEY (`entity_id`) REFERENCES `client_entities` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_sig_req_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_sig_req_signed_doc` FOREIGN KEY (`signed_document_id`) REFERENCES `documents` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `signature_signers` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `request_id` INT UNSIGNED NOT NULL,
    `user_id` INT UNSIGNED NULL,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `role` ENUM('signer', 'approver', 'viewer', 'cc') NOT NULL DEFAULT 'signer',
    `signing_order` INT UNSIGNED NOT NULL DEFAULT 1,
    `token` VARCHAR(64) NOT NULL UNIQUE,
    `status` ENUM('pending', 'signed', 'declined', 'expired') NOT NULL DEFAULT 'pending',
    `read_status` ENUM('not_opened', 'opened') NOT NULL DEFAULT 'not_opened',
    `sent_at` DATETIME NULL,
    `opened_at` DATETIME NULL,
    `signed_at` DATETIME NULL,
    `declined_at` DATETIME NULL,
    `decline_reason` TEXT NULL,
    `ip_address` VARCHAR(45) NULL,
    `user_agent` VARCHAR(255) NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_signers_req` (`request_id`),
    INDEX `idx_signers_token` (`token`),
    INDEX `idx_signers_email` (`email`),
    INDEX `idx_signers_status` (`status`),
    CONSTRAINT `fk_signers_req` FOREIGN KEY (`request_id`) REFERENCES `signature_requests` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_signers_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `signature_fields` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `request_id` INT UNSIGNED NOT NULL,
    `signer_id` INT UNSIGNED NOT NULL,
    `type` ENUM('signature', 'initials', 'name', 'email', 'date', 'text', 'checkbox') NOT NULL DEFAULT 'signature',
    `page` INT UNSIGNED NOT NULL DEFAULT 1,
    `position_x` DECIMAL(6, 3) NOT NULL DEFAULT 0.000,
    `position_y` DECIMAL(6, 3) NOT NULL DEFAULT 0.000,
    `width` DECIMAL(6, 3) NOT NULL DEFAULT 20.000,
    `height` DECIMAL(6, 3) NOT NULL DEFAULT 6.000,
    `custom_text` TEXT NULL,
    `signature_data` LONGTEXT NULL,
    `signature_type` ENUM('drawn', 'typed', 'uploaded') NULL,
    `required` TINYINT(1) NOT NULL DEFAULT 1,
    `inserted` TINYINT(1) NOT NULL DEFAULT 0,
    `signed_at` DATETIME NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_sig_fields_req` (`request_id`),
    INDEX `idx_sig_fields_signer` (`signer_id`),
    INDEX `idx_sig_fields_page` (`page`),
    CONSTRAINT `fk_sig_fields_req` FOREIGN KEY (`request_id`) REFERENCES `signature_requests` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_sig_fields_signer` FOREIGN KEY (`signer_id`) REFERENCES `signature_signers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `signature_audit_events` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `request_id` INT UNSIGNED NOT NULL,
    `signer_id` INT UNSIGNED NULL,
    `user_id` INT UNSIGNED NULL,
    `event_type` VARCHAR(50) NOT NULL,
    `event_description` TEXT NOT NULL,
    `metadata` JSON NULL,
    `ip_address` VARCHAR(45) NULL,
    `user_agent` VARCHAR(255) NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_sig_audit_req` (`request_id`),
    INDEX `idx_sig_audit_type` (`event_type`),
    INDEX `idx_sig_audit_created` (`created_at`),
    CONSTRAINT `fk_sig_audit_req` FOREIGN KEY (`request_id`) REFERENCES `signature_requests` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_sig_audit_signer` FOREIGN KEY (`signer_id`) REFERENCES `signature_signers` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_sig_audit_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
